all: sortvec sortbin

sortvec: sortvec.cpp
	g++ -std=c++11 -Ofast -o sortvec -fomit-frame-pointer sortvec.cpp

sortbin: sortbin.cpp
	g++ -std=c++11 -Ofast -o sortbin -fomit-frame-pointer sortbin.cpp
clean:
	rm sortvec
